### ISSUE TITLE
Crash due to transient dependency to old version of `prismatic/schema`

### ISSUE THREAD

**Issue by grav** [nervous-systems/fink-nottle#17]
Can be fixed by bumping `eulalie` after this is merged:
https://github.com/nervous-systems/eulalie/pull/43

**Comment by moea** [comment]
Can you `:exclude` eulalie and explicitly depend on 0.6.11-SNAPSHOT?  If that fixes your problem, I'll release a fink-nottle snapshot pointing at it.

**Comment by grav** [comment]
Yes, I can confirm that this works.

**Comment by moea** [comment]
0.4.8-SNAPSHOT pushed to clojars.

**Comment by grav** [comment]
Thanks!
