### ISSUE TITLE
duplicate defmethod in fink-nottle.sqs.tagged

### ISSUE THREAD

**Issue by sirobinson** [nervous-systems/fink-nottle#3]
Should the final line here:
(defmulti  message-in (fn [tag body] tag))
(defmethod message-in :default [_ body] body)
(defmulti  message-out (fn [tag body] tag))
(defmethod message-in :default [_ body] body)

be (defmethod message-out .....

rather than message-in?

**Comment by moea** [comment]
Thanks, well spotted.  I'll fix it once I've finished/released the Clojurescript port which is hanging out in master - a day or two.

**Comment by sirobinson** [comment]
Wow

Thanks for quick response!

**Comment by moea** [comment]
Fixed in 0.4.1
